require:
  - 'rubocop-rspec'
  - 'test_prof/rubocop'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'

FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: 'when_needed'

Metrics/LineLength:
  Exclude:
    - 'Gemfile'
    - 'config/initializers/*'
    - 'db/seeds.rb'
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/**/*.rb'

MultilineOperationIndentation:
  EnforcedStyle: 'indented'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Rails:
  Enabled: true

RSpec/AggregateFailures:
  Enabled: true
  Include:
    - 'spec/**/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/routing/*'
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 3

StringLiterals:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/forms/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/*'
    - 'bin/*'
    - 'build/**/*'
    - 'config/**/*'
    - 'config/application.rb'
    - 'db/**/*'
    - 'deploy/**/*'
    - 'doc/**/*'
    - 'docker/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused.rb$/

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'Guardfile'

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
  Exclude:
    - 'Guardfile'
