default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>

development:
  <<: *default
  database: stimulating_development

test:
  <<: *default
  database: stimulating_test

production:
  <<: *default
  database: stimulating_production
  password: <%= ENV['stimulating_DATABASE_PASSWORD'] %>
